const languages = { zh:{code:'CHN',name:'Chinese',locale:'zh-CN'}, en:{code:'ENG',name:'English',locale:'en-US'}, es:{code:'ESP',name:'Spanish',locale:'es-ES'}, fr:{code:'FRA',name:'French',locale:'fr-FR'} };
const starters = [{from:'en',to:'zh'},{from:'zh',to:'en'},{from:'en',to:'es'},{from:'es',to:'fr'}];
const grid=document.querySelector('.translation-grid'), toast=document.querySelector('.toast'), themeButton=document.querySelector('.theme'), themeMeta=document.querySelector('meta[name="theme-color"]');
const debounceTimers=new WeakMap(), requestVersions=new WeakMap(), translatorCache=new Map();

function languageOptions(selected){return Object.entries(languages).map(([id,lang])=>`<option value="${id}" ${id===selected?'selected':''}>${lang.code} — ${lang.name}</option>`).join('')}
function createWindow(config,index){return `<article class="translator-window" data-index="${index}"><div class="window-head"><div class="window-title"><span>0${index+1}</span><strong>Translator</strong></div><div class="language-controls"><label class="language-pick"><small>From</small><select class="from-language" aria-label="Translator ${index+1} source language">${languageOptions(config.from)}</select></label><button class="swap" type="button" aria-label="Swap source and target languages" title="Swap languages"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 7h12m0 0-3-3m3 3-3 3M17 17H5m0 0 3-3m-3 3 3 3"/></svg></button><label class="language-pick"><small>To</small><select class="to-language" aria-label="Translator ${index+1} target language">${languageOptions(config.to)}</select></label></div><button class="clear-one" type="button" aria-label="Clear translator ${index+1}">Clear</button></div><div class="window-body"><div class="input-side"><span class="field-label">Original</span><textarea maxlength="500" aria-label="Translator ${index+1} text input" placeholder="Start writing…" spellcheck="true"></textarea><div class="side-foot"><span class="count">0 / 500</span><span class="live-label">Live</span></div></div><div class="output-side"><span class="field-label">Translation</span><div class="output placeholder" aria-live="polite">Your translation will appear here.</div><div class="side-foot"><span class="window-status">Ready</span><div class="card-actions"><button class="icon-button speak" type="button" aria-label="Listen to translation" title="Listen" disabled><svg viewBox="0 0 24 24"><path d="M11 5 6 9H3v6h3l5 4V5Zm4 5a4 4 0 0 1 0 4m2.5-6.5a7 7 0 0 1 0 9"/></svg></button><button class="icon-button copy" type="button" aria-label="Copy translation" title="Copy" disabled><svg viewBox="0 0 24 24"><rect x="8" y="8" width="11" height="11" rx="1"/><path d="M16 8V5H5v11h3"/></svg></button></div></div></div></div></article>`}

async function translateWindow(translator){const text=translator.querySelector('textarea').value.trim(),from=translator.querySelector('.from-language').value,to=translator.querySelector('.to-language').value,status=translator.querySelector('.window-status');const version=(requestVersions.get(translator)||0)+1;requestVersions.set(translator,version);if(!text){showEmpty(translator);return}if(from===to){setState(translator,text,'','Same language');return}setState(translator,'Finding the right words…','loading','Translating');try{const result=await translateText(text,from,to,status);if(requestVersions.get(translator)!==version)return;setState(translator,result.text,'',result.method)}catch(error){if(requestVersions.get(translator)!==version)return;setState(translator,'Translation is temporarily unavailable.','error','Try again');console.error(error)}}
async function translateText(text,from,to,status){if('Translator'in self&&window.isSecureContext){try{const translator=await getTranslator(from,to,status);return{text:await translator.translate(text),method:'On-device'}}catch(error){console.info('On-device translation unavailable; using cloud fallback.',error)}}status.textContent='Translating';const params=new URLSearchParams({q:text,langpair:`${from}|${to}`,mt:'1'});const response=await fetch(`https://api.mymemory.translated.net/get?${params}`);if(!response.ok)throw new Error(`Translation service returned ${response.status}`);const data=await response.json();if(data.responseStatus!==200||!data.responseData?.translatedText)throw new Error(data.responseDetails||'No translation returned');return{text:decodeHtml(data.responseData.translatedText),method:'Cloud translation'}}
async function getTranslator(from,to,status){const key=`${from}:${to}`;if(translatorCache.has(key))return translatorCache.get(key);const availability=await Translator.availability({sourceLanguage:from,targetLanguage:to});if(availability==='unavailable')throw new Error('MODEL_UNAVAILABLE');const creation=Translator.create({sourceLanguage:from,targetLanguage:to,monitor(monitor){monitor.addEventListener('downloadprogress',event=>{status.textContent=`Downloading ${Math.round(event.loaded*100)}%`})}});translatorCache.set(key,creation);try{const translator=await creation;translatorCache.set(key,translator);return translator}catch(error){translatorCache.delete(key);throw error}}
function queueTranslation(translator,delay=450){clearTimeout(debounceTimers.get(translator));debounceTimers.set(translator,setTimeout(()=>translateWindow(translator),delay))}
function setState(translator,message,state,label){const output=translator.querySelector('.output'),status=translator.querySelector('.window-status');output.textContent=message;output.className=`output ${state}`.trim();status.textContent=label;status.className=`window-status ${state}`.trim();translator.querySelectorAll('.card-actions button').forEach(button=>{button.disabled=Boolean(state)})}
function showEmpty(translator){setState(translator,'Your translation will appear here.','placeholder','Ready')}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),1600)}

grid.addEventListener('click',async event=>{const translator=event.target.closest('.translator-window');if(!translator)return;if(event.target.closest('.clear-one')){translator.querySelector('textarea').value='';translator.querySelector('.count').textContent='0 / 500';requestVersions.set(translator,(requestVersions.get(translator)||0)+1);showEmpty(translator);translator.querySelector('textarea').focus();return}if(event.target.closest('.swap')){const from=translator.querySelector('.from-language'),to=translator.querySelector('.to-language');[from.value,to.value]=[to.value,from.value];const output=translator.querySelector('.output');if(!output.classList.contains('placeholder')&&!output.classList.contains('error')&&!output.classList.contains('loading')){translator.querySelector('textarea').value=output.textContent;translator.querySelector('.count').textContent=`${output.textContent.length} / 500`}showEmpty(translator);queueTranslation(translator,0)}const outputText=translator.querySelector('.output').textContent;if(event.target.closest('.copy')){try{await navigator.clipboard.writeText(outputText);showToast('Translation copied')}catch{showToast('Copy unavailable')}}if(event.target.closest('.speak')&&'speechSynthesis'in window){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(outputText);utterance.lang=languages[translator.querySelector('.to-language').value].locale;speechSynthesis.speak(utterance)}});
grid.addEventListener('input',event=>{if(!event.target.matches('textarea'))return;const translator=event.target.closest('.translator-window');translator.querySelector('.count').textContent=`${event.target.value.length} / 500`;if(!event.target.value.trim())showEmpty(translator);else queueTranslation(translator)});
grid.addEventListener('change',event=>{if(event.target.matches('.from-language, .to-language'))queueTranslation(event.target.closest('.translator-window'),0)});
document.querySelector('.clear-all').addEventListener('click',()=>{grid.querySelectorAll('.translator-window').forEach(translator=>{translator.querySelector('textarea').value='';translator.querySelector('.count').textContent='0 / 500';requestVersions.set(translator,(requestVersions.get(translator)||0)+1);showEmpty(translator)});showToast('All windows cleared')});
function applyTheme(theme){const dark=theme==='dark';document.body.classList.toggle('dark',dark);themeButton.setAttribute('aria-label',dark?'Switch to light mode':'Switch to dark mode');themeMeta.setAttribute('content',dark?'#101612':'#f2efe6');localStorage.setItem('vox-theme',theme)}
themeButton.addEventListener('click',()=>applyTheme(document.body.classList.contains('dark')?'light':'dark'));
function decodeHtml(value){const el=document.createElement('textarea');el.innerHTML=value;return el.value}
const savedTheme=localStorage.getItem('vox-theme'),preferredTheme=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';applyTheme(savedTheme||preferredTheme);grid.innerHTML=starters.map(createWindow).join('');
